version: '3.8'

services:
  api-gateway:
    build:
      context: ./services/api-gateway
      target: development
    volumes:
      - ./services/api-gateway:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - DEBUG=*

  user-service:
    volumes:
      - ./services/user-service:/app
    environment:
      - GO_ENV=development

  product-service:
    volumes:
      - ./services/product-service:/app
    environment:
      - PYTHON_ENV=development
      - DEBUG=true

  notification-service:
    volumes:
      - ./services/notification-service:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - DEBUG=*

  # Development tools
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - microservices

  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
    depends_on:
      - redis
    networks:
      - microservices
